### ISSUE TITLE
Antivirus Software Blocking Moss

### ISSUE THREAD

**Issue by stephenpurkiss** [lightningrodlabs/moss#78]
### Problem/Motivation

My support worker has [Avast](https://www.avast.com) on her Windows system and has to use it as part of her business insurance. This meant we couldn't continue until some unknown human made the decision as to whether we were allowed to according to unknown criteria. This absolutely did not trigger me at all...

So she submitted the whatever thing she had to submit and said oh usually it only takes a few minutes. 24h later we finally were allowed to use Moss, and apparently this means that anyone else who uses this Avast system also can now they've deemed it OK. So I thought you might like to know as this issue may arise elsewhere with other software.

### Steps to reproduce

Try using Moss where there's a system that restricts the software you're allowed to use on your own computer and where you have absolutely zero control over it because otherwise your insurance is invalid.

**Comment by matthme** [comment]
Thank you for sharing this! I can equally ensure you that such things also absolutely would not trigger me at all, never have in the past and never shall in the future. But it's at least good to hear that it got accepted at all in the end :) I guess all we can do for now is trying to make sure that we keep an image of being a trustworthy project...

**Comment by stephenpurkiss** [comment]
> Thank you for sharing this! I can equally ensure you that such things also absolutely would not trigger me at all, never have in the past and never shall in the future. But it's at least good to hear that it got accepted at all in the end :) I guess all we can do for now is trying to make sure that we keep an image of being a trustworthy project...

🤣
